### ISSUE TITLE
KeyError: "name='csrftoken', domain=None, path=None

### ISSUE THREAD

**Issue by aodecipher** [ollipa/memrise-audio-uploader#9]
I've authorized the gcloud default-application login through
`gcloud auth application-default login`
But when I run `python3.11 -m memrise_audio_uploaderploader`
It still gives me the error in the title.

Error printout:
Using stored password
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/memrise_audio_uploader/__main__.py", line 16, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/memrise_audio_uploader/cli.py", line 141, in main
    memrise_client = memrise_login()
                     ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memrise_audio_uploader/cli.py", line 37, in memrise_login
    memrise_client = memrise.MemriseClient(settings.memrise_username, settings.memrise_password)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memrise_audio_uploader/lib/memrise/client.py", line 176, in __init__
    self._login(username, password)
  File "/usr/local/lib/python3.11/site-packages/memrise_audio_uploader/lib/memrise/client.py", line 212, in _login
    "csrfmiddlewaretoken": response.cookies["csrftoken"],
                           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by ollipa** [comment]
Hi @aodecipher! It seems that Memrise has updated their login API and removed some old endpoints. I'll need to reverse engineer the new API endpoints to get this working again.

**Comment by ollipa** [comment]
Memrise had updated the login code and removed the endpoint that was used for listing courses. The latest release fixes these issues.
